= Controlled Vocabulary

== Definition

// #TODO#: This should be formalized in a model, and the diagram should be generated from that.

.Informal conceptual model of a controlled vocabulary
[d2,format=svg,theme=5,width=70%]
----
vars: {
    d2-config: {
        pad: 30
        center: true
    }
}
Controlled vocabulary --> Term : hasPart
----

.Types of controlled vocabularies
include::partial$controlled-vocabulary/diagram-types-vocabs.adoc[]

== Identification

The considerations and justifications for the choices made are documented xref:controlled-vocabulary/index.adoc[here].

NOTE: All URI templates conform to <<RFC6570>>.

include::partial$controlled-vocabulary/uri-templates.adoc[]

'''

include::example$energiesysteembeheer-thesaurus-uris.adoc[]

== Representation

[cols="h,2,2"]
|===
| Resource | Machine-processable | Human-readable

| Controlled vocabulary
| SKOS, RDF
| BegrippenXL, HTML

| Vocabulary term
| _n/a_
| _n/a_

|===

== Versioning

Controlled vocabularies follow an evolution strategy where breaking changes are never allowed.

Through deprecation and introduction of new URIs and statements, newer and older versions of the vocabulary model all live in one schema.

